### ISSUE TITLE
Add product.product relation to forecast model

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/forecast#56]
## Feature

```gherkin
As a Forecast Manager
I want to correctly extract the Stock History data as Forecast Data.
So that the product demand forecast functionality work correctly
```
## Deliverables

Correspond to HU#913 CA#8.

## Solution

For that is necessary to add a relation from forecast model to product.product and make this new field the main one used in all forecast methods instead product.template field. 

The product template relation should be maintain as a secondary product field that add the usability benefit to easy manage/access all the product template variants forecasts from the product form view (product.template).

## TODO

- [x] Add new product_id field to product.product in the forecast model.
- [x] Modify the product_tmpl_id field as a related field to the product_id field.
- [x] Update default product method to use product_id field.
- [x] Update the display name compute method to work con product_id field.
- [x] Update the forecast views to add product_id field.
- [x] Update the forecast views to re-order product_tmpl_id field.
- [x] Update unit test to work with product_id instead product_tmpl_id.
- [x] Add search simple/groupby filters by product/product template to be easy to run the functional tests.
- [x] Update demo data to make that the test have logic. Remove references to product_tmpl_id and use the product_id.
- [x] Update manual forecast demo data and link to product variants of the same product template.
- [x] Update/Add ir action windows to manage the button Forecasting from the product variant and product template form views.

After Review:

- [x] remove required attribute from the forecast.product_id field.
