### ISSUE TITLE
Usability: Improve Interaction with Forecast Views

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/forecast#57]
## Feature

```gherkin

As a Forecast Manager
I want to list all forecast records and easily identify the forecast purpose/results.
So that the forecast list can be clean and readable.

As a Forecast Manager
I want to differentiate from a Forecast with manual data with rule generated data.
So that can easy review the forecast results.

As a Forecast Manager
I want to have a more compact and clean Forecast form, only show my interests. 
So that can be more redeable and easy to use.
```
## Deliverables

Correspont to HU#913 CA#8.

## Solution

The current forecast list view have a lot of information that do not fit in the regular page size. The solution is to make invisible some results in the view and to make the name field larger so can easily identify the forecast.

We will also add the manual data field to the list view to identify quickly the type of forecast input data. Add some filters to search by and group by manual data and rule generated data.

The forecast form show Forecasting Data panel that is empty. Is only fill if the `Show Help` or `Show Mathematical Base Help` checkbox are active. Hide this section and only show when is needed could be a way to read easily the forecast form view.

## TODO

- [x] hide the forecast ma error columns in the tree view.
- [x] show Boolean manual data field in the tree view.
- [x] add filter to search by forecast manual data type in the search view.
- [x] add filter to search by forecast rule generated data type in the search view.
- [x] hide/show Forecasting Data panel only in show help or show help math base  fields are set in the form view.
- [x] update forecast demo data to indicate what is the context of the forecast and make the user easily understand how forecasting works. 
- [x] Show value_ids in forecast tree view. Now we can now the quantity of values data used to calculate a forecast.
