### ISSUE TITLE
Standardize stock.forecast model and add demo data to test 

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/forecast#58]
## Feature

```gherkin
As a Forecast User
I want that stock demand results only show me the demand lines
So that the forecast values are loaded correctly,

As a Forecast User and Developer
I want that see demand forecast demo data
So that can understand the forecast functionalities and planning new development steps
```

## Deliverables

Correspond to HU#913 CA#8.

## Solution

To not generate any confusion:

- `stock.demand` wizard will be rename with the prefix `wizard`.
- `quantity_required` field name will be fix to `quantity_onstock` that is the real value of the field.

To only show the demand the result of the stock.demand need to be filter with the negatives quantity: that represent a demand.

We need to add demo data to test the new stock.demand and how it works with the forecast values, for that:

- Generate at least 80 stock.picking entries.
- Pickings must be associated to the last 3 months.
- Select 5 products from odoo modules data demo and random use then in the pickings entries.
- Create pickings for: production, supplier, customer, internal and returns.
- Create pickins for different locations. 
- Add new forecast demo (rule/filter/forecast record) one for every product in the test and ensure that the forecast values/results are loaded with the demo data (Simulate Click the Fill Values button).

In a technical scope is necessary to find all the demo data records to be re use and list the xml ids (products, locations, picking types, etc). The find a way to make a permute of this values. For that will create a sheet file (With Calc). 

## TODO

- [x] Rename `stock.demand` wizard to `wizard.stock.demand`.
- [x] Rename field `quantity_required` in `stock.history` to `quantity_onstock`.
- [x] Filter the results of `stock.demand` to only show out operations (the demand).
- [x] Create sheet file with the permute of the picking demo data. 
- [x] Add stock.picking data demo to test the forecasts for 5 products.
- [x] Add new 5 forecast/filter/rule, one for every product set in the demo data.
- [x] Check that the demo data runs properly and fill the forecast values with the demo data introduced.

After finish:

- [x] Update the module description TODO list, remove/add elements.
- [x] Add new subsection named features to identify the new functionalities added in the module.
- [x] Delete repeat help and images about forecast works, and make a reference to forecast module.
- [x] Update links reference to old repository stock-forecasting, module name and module version.
- [x] Re-order the level of the contributors and maintainer sections.

After review:
- [x] way workaround to make all the stock pickings generate in a past date instead the current date. Create POC overwriting the date parameter in the [action_done](https://github.com/odoo/odoo/blob/8.0/addons/stock/stock.py#L2469) method to accomplish this point.
- [x] update data demo 80 per product/location.
- [x] add help to the module description to indicate how the forecast demand need to be generated manually using stock.demand wizard.
- [x] update open_table() wizard.stock.demand to add context to generate automatically the the filter to use in the forecast. 
- [x] **NOTE: I could not generate a default filter to a date range. This need to be resolve in another way.**. This will be fix as part of a new issue #66.
- [x] show [screenshot](http://www.awesomescreenshot.com/image/625306/bf11ee63d23fee6191da75e89943f5ac) error Quantity avaliable results to @josemoralesp.
- [x] change the quantity sign to manage positive amounts instead of negative amount. this is affecting the forecast demands to generate bad forecast.
- [x] remove the overwrite of the string attribute in the stock demand columns. 
- [x] Create a demo rule to indicate "Demand for the last 14 days for X product". domain [('date', '=', today()), '(date', '']. **NOTE: validaton how to make this today() shortcut in the domain.**. Add unit test to check if the result is correct.
 - [x] Update data demo to have 80 pickings per product/location

**Comment by zaoral** [comment]
Fixed cdf973f089d3ff7d471974a531bf39e327741a41
